-- ----------------------------
-- 老师帮 teach:* / ast:* / common:file:* 菜单与按钮权限种子
-- 由 sql/gen_teach_sql.py 扫描 Controller 中 CheckUserInterfaceAuth 生成
-- 生成日期 2026-10-09
-- 菜单ID段 5000-5999；重复执行时按主键更新名称/权限，不影响已分配给角色的关系（sys_role_menu）
-- 超级管理员拥有 *:*:*，无需分配；其他角色请在“角色管理”中勾选对应按钮
-- ----------------------------

insert into sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) values
(5000, '老师帮业务权限', 0, 90, 'teacher-help-perm', null, null, '', 1, 0, 'M', '1', '0', null, 'education', 'admin', sysdate(), '', null, '业务接口权限容器（PC 端业务页面为静态路由，本目录默认隐藏，仅用于角色分配按钮权限）'),
(5001, '学员管理', 5000, 1, 'student', null, null, '', 1, 0, 'M', '1', '0', null, '#', 'admin', sysdate(), '', null, 'teach:student:*'),
(5100, '学员管理新增', 5001, 1, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:student:add', '#', 'admin', sysdate(), '', null, ''),
(5101, '学员管理修改', 5001, 2, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:student:edit', '#', 'admin', sysdate(), '', null, ''),
(5102, '学员管理导出', 5001, 3, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:student:export', '#', 'admin', sysdate(), '', null, ''),
(5103, '学员管理列表', 5001, 4, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:student:list', '#', 'admin', sysdate(), '', null, ''),
(5104, '学员管理查询', 5001, 5, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:student:query', '#', 'admin', sysdate(), '', null, ''),
(5105, '学员管理删除', 5001, 6, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:student:remove', '#', 'admin', sysdate(), '', null, ''),
(5002, '家长管理', 5000, 2, 'parent', null, null, '', 1, 0, 'M', '1', '0', null, '#', 'admin', sysdate(), '', null, 'teach:parent:*'),
(5106, '家长管理新增', 5002, 1, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:parent:add', '#', 'admin', sysdate(), '', null, ''),
(5107, '家长管理修改', 5002, 2, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:parent:edit', '#', 'admin', sysdate(), '', null, ''),
(5108, '家长管理导出', 5002, 3, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:parent:export', '#', 'admin', sysdate(), '', null, ''),
(5109, '家长管理列表', 5002, 4, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:parent:list', '#', 'admin', sysdate(), '', null, ''),
(5110, '家长管理查询', 5002, 5, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:parent:query', '#', 'admin', sysdate(), '', null, ''),
(5111, '家长管理删除', 5002, 6, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:parent:remove', '#', 'admin', sysdate(), '', null, ''),
(5003, '老师管理', 5000, 3, 'teacher', null, null, '', 1, 0, 'M', '1', '0', null, '#', 'admin', sysdate(), '', null, 'teach:teacher:*'),
(5112, '老师管理新增', 5003, 1, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:teacher:add', '#', 'admin', sysdate(), '', null, ''),
(5113, '老师管理修改', 5003, 2, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:teacher:edit', '#', 'admin', sysdate(), '', null, ''),
(5114, '老师管理导出', 5003, 3, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:teacher:export', '#', 'admin', sysdate(), '', null, ''),
(5115, '老师管理列表', 5003, 4, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:teacher:list', '#', 'admin', sysdate(), '', null, ''),
(5116, '老师管理查询', 5003, 5, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:teacher:query', '#', 'admin', sysdate(), '', null, ''),
(5117, '老师管理删除', 5003, 6, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:teacher:remove', '#', 'admin', sysdate(), '', null, ''),
(5004, '班级管理', 5000, 4, 'class', null, null, '', 1, 0, 'M', '1', '0', null, '#', 'admin', sysdate(), '', null, 'teach:class:*'),
(5118, '班级管理新增', 5004, 1, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:class:add', '#', 'admin', sysdate(), '', null, ''),
(5119, '班级管理修改', 5004, 2, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:class:edit', '#', 'admin', sysdate(), '', null, ''),
(5120, '班级管理列表', 5004, 3, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:class:list', '#', 'admin', sysdate(), '', null, ''),
(5121, '班级管理查询', 5004, 4, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:class:query', '#', 'admin', sysdate(), '', null, ''),
(5122, '班级管理删除', 5004, 5, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:class:remove', '#', 'admin', sysdate(), '', null, ''),
(5005, '课程管理', 5000, 5, 'course', null, null, '', 1, 0, 'M', '1', '0', null, '#', 'admin', sysdate(), '', null, 'teach:course:*'),
(5123, '课程管理新增', 5005, 1, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:course:add', '#', 'admin', sysdate(), '', null, ''),
(5124, '课程管理修改', 5005, 2, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:course:edit', '#', 'admin', sysdate(), '', null, ''),
(5125, '课程管理导出', 5005, 3, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:course:export', '#', 'admin', sysdate(), '', null, ''),
(5126, '课程管理列表', 5005, 4, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:course:list', '#', 'admin', sysdate(), '', null, ''),
(5127, '课程管理查询', 5005, 5, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:course:query', '#', 'admin', sysdate(), '', null, ''),
(5128, '课程管理删除', 5005, 6, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:course:remove', '#', 'admin', sysdate(), '', null, ''),
(5006, '排课管理', 5000, 6, 'schedule-event', null, null, '', 1, 0, 'M', '1', '0', null, '#', 'admin', sysdate(), '', null, 'teach:schedule:event:*'),
(5129, '排课管理新增', 5006, 1, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:schedule:event:add', '#', 'admin', sysdate(), '', null, ''),
(5130, '排课管理修改', 5006, 2, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:schedule:event:edit', '#', 'admin', sysdate(), '', null, ''),
(5131, '排课管理列表', 5006, 3, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:schedule:event:list', '#', 'admin', sysdate(), '', null, ''),
(5132, '排课管理查询', 5006, 4, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:schedule:event:query', '#', 'admin', sysdate(), '', null, ''),
(5133, '排课管理删除', 5006, 5, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:schedule:event:remove', '#', 'admin', sysdate(), '', null, ''),
(5007, '考勤管理', 5000, 7, 'schedule-attendance', null, null, '', 1, 0, 'M', '1', '0', null, '#', 'admin', sysdate(), '', null, 'teach:schedule:attendance:*'),
(5134, '考勤管理签到', 5007, 1, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:schedule:attendance:checkin', '#', 'admin', sysdate(), '', null, ''),
(5135, '考勤管理列表', 5007, 2, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:schedule:attendance:list', '#', 'admin', sysdate(), '', null, ''),
(5136, '考勤管理补签', 5007, 3, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:schedule:attendance:manual', '#', 'admin', sysdate(), '', null, ''),
(5137, '考勤管理统计', 5007, 4, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:schedule:attendance:stat', '#', 'admin', sysdate(), '', null, ''),
(5008, '上课记录', 5000, 8, 'class-record', null, null, '', 1, 0, 'M', '1', '0', null, '#', 'admin', sysdate(), '', null, 'teach:classRecord:*'),
(5138, '上课记录列表', 5008, 1, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:classRecord:list', '#', 'admin', sysdate(), '', null, ''),
(5139, '上课记录查询', 5008, 2, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:classRecord:query', '#', 'admin', sysdate(), '', null, ''),
(5009, '会员卡管理', 5000, 9, 'card', null, null, '', 1, 0, 'M', '1', '0', null, '#', 'admin', sysdate(), '', null, 'teach:card:*'),
(5140, '会员卡管理新增', 5009, 1, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:card:add', '#', 'admin', sysdate(), '', null, ''),
(5141, '会员卡管理修改', 5009, 2, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:card:edit', '#', 'admin', sysdate(), '', null, ''),
(5142, '会员卡管理发放', 5009, 3, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:card:grant', '#', 'admin', sysdate(), '', null, ''),
(5143, '会员卡管理列表', 5009, 4, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:card:list', '#', 'admin', sysdate(), '', null, ''),
(5144, '会员卡管理查询', 5009, 5, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:card:query', '#', 'admin', sysdate(), '', null, ''),
(5145, '会员卡管理删除', 5009, 6, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:card:remove', '#', 'admin', sysdate(), '', null, ''),
(5900, '会员卡管理核销', 5009, 7, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:card:consume', '#', 'admin', sysdate(), '', null, ''),
(5010, '场地管理', 5000, 10, 'venue', null, null, '', 1, 0, 'M', '1', '0', null, '#', 'admin', sysdate(), '', null, 'teach:venue:*'),
(5146, '场地管理新增', 5010, 1, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:venue:add', '#', 'admin', sysdate(), '', null, ''),
(5147, '场地管理修改', 5010, 2, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:venue:edit', '#', 'admin', sysdate(), '', null, ''),
(5148, '场地管理列表', 5010, 3, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:venue:list', '#', 'admin', sysdate(), '', null, ''),
(5149, '场地管理查询', 5010, 4, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:venue:query', '#', 'admin', sysdate(), '', null, ''),
(5150, '场地管理删除', 5010, 5, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:venue:remove', '#', 'admin', sysdate(), '', null, ''),
(5011, '课后点评', 5000, 11, 'comment', null, null, '', 1, 0, 'M', '1', '0', null, '#', 'admin', sysdate(), '', null, 'teach:comment:*'),
(5151, '课后点评新增', 5011, 1, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:comment:add', '#', 'admin', sysdate(), '', null, ''),
(5152, '课后点评修改', 5011, 2, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:comment:edit', '#', 'admin', sysdate(), '', null, ''),
(5153, '课后点评列表', 5011, 3, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:comment:list', '#', 'admin', sysdate(), '', null, ''),
(5154, '课后点评查询', 5011, 4, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:comment:query', '#', 'admin', sysdate(), '', null, ''),
(5155, '课后点评删除', 5011, 5, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:comment:remove', '#', 'admin', sysdate(), '', null, ''),
(5012, '请假管理', 5000, 12, 'leave', null, null, '', 1, 0, 'M', '1', '0', null, '#', 'admin', sysdate(), '', null, 'teach:leave:*'),
(5156, '请假管理新增', 5012, 1, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:leave:add', '#', 'admin', sysdate(), '', null, ''),
(5157, '请假管理修改', 5012, 2, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:leave:edit', '#', 'admin', sysdate(), '', null, ''),
(5158, '请假管理列表', 5012, 3, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:leave:list', '#', 'admin', sysdate(), '', null, ''),
(5159, '请假管理查询', 5012, 4, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:leave:query', '#', 'admin', sysdate(), '', null, ''),
(5160, '请假管理删除', 5012, 5, '#', null, null, '', 1, 0, 'F', '0', '0', 'teach:leave:remove', '#', 'admin', sysdate(), '', null, ''),
(5013, '物品管理', 5000, 13, 'item', null, null, '', 1, 0, 'M', '1', '0', null, '#', 'admin', sysdate(), '', null, 'ast:item:*'),
(5161, '物品管理新增', 5013, 1, '#', null, null, '', 1, 0, 'F', '0', '0', 'ast:item:add', '#', 'admin', sysdate(), '', null, ''),
(5162, '物品管理修改', 5013, 2, '#', null, null, '', 1, 0, 'F', '0', '0', 'ast:item:edit', '#', 'admin', sysdate(), '', null, ''),
(5163, '物品管理导出', 5013, 3, '#', null, null, '', 1, 0, 'F', '0', '0', 'ast:item:export', '#', 'admin', sysdate(), '', null, ''),
(5164, '物品管理列表', 5013, 4, '#', null, null, '', 1, 0, 'F', '0', '0', 'ast:item:list', '#', 'admin', sysdate(), '', null, ''),
(5165, '物品管理查询', 5013, 5, '#', null, null, '', 1, 0, 'F', '0', '0', 'ast:item:query', '#', 'admin', sysdate(), '', null, ''),
(5166, '物品管理删除', 5013, 6, '#', null, null, '', 1, 0, 'F', '0', '0', 'ast:item:remove', '#', 'admin', sysdate(), '', null, ''),
(5014, '出入库管理', 5000, 14, 'inventory', null, null, '', 1, 0, 'M', '1', '0', null, '#', 'admin', sysdate(), '', null, 'ast:inventory:*'),
(5167, '出入库管理新增', 5014, 1, '#', null, null, '', 1, 0, 'F', '0', '0', 'ast:inventory:add', '#', 'admin', sysdate(), '', null, ''),
(5168, '出入库管理修改', 5014, 2, '#', null, null, '', 1, 0, 'F', '0', '0', 'ast:inventory:edit', '#', 'admin', sysdate(), '', null, ''),
(5169, '出入库管理导出', 5014, 3, '#', null, null, '', 1, 0, 'F', '0', '0', 'ast:inventory:export', '#', 'admin', sysdate(), '', null, ''),
(5170, '出入库管理导入', 5014, 4, '#', null, null, '', 1, 0, 'F', '0', '0', 'ast:inventory:import', '#', 'admin', sysdate(), '', null, ''),
(5171, '出入库管理列表', 5014, 5, '#', null, null, '', 1, 0, 'F', '0', '0', 'ast:inventory:list', '#', 'admin', sysdate(), '', null, ''),
(5172, '出入库管理查询', 5014, 6, '#', null, null, '', 1, 0, 'F', '0', '0', 'ast:inventory:query', '#', 'admin', sysdate(), '', null, ''),
(5015, '费用管理', 5000, 15, 'fee', null, null, '', 1, 0, 'M', '1', '0', null, '#', 'admin', sysdate(), '', null, 'ast:fee:*'),
(5173, '费用管理新增', 5015, 1, '#', null, null, '', 1, 0, 'F', '0', '0', 'ast:fee:add', '#', 'admin', sysdate(), '', null, ''),
(5174, '费用管理修改', 5015, 2, '#', null, null, '', 1, 0, 'F', '0', '0', 'ast:fee:edit', '#', 'admin', sysdate(), '', null, ''),
(5175, '费用管理列表', 5015, 3, '#', null, null, '', 1, 0, 'F', '0', '0', 'ast:fee:list', '#', 'admin', sysdate(), '', null, ''),
(5176, '费用管理查询', 5015, 4, '#', null, null, '', 1, 0, 'F', '0', '0', 'ast:fee:query', '#', 'admin', sysdate(), '', null, ''),
(5177, '费用管理删除', 5015, 5, '#', null, null, '', 1, 0, 'F', '0', '0', 'ast:fee:remove', '#', 'admin', sysdate(), '', null, ''),
(5016, '通用文件', 5000, 16, 'file', null, null, '', 1, 0, 'M', '1', '0', null, '#', 'admin', sysdate(), '', null, 'common:file:*'),
(5178, '通用文件下载', 5016, 1, '#', null, null, '', 1, 0, 'F', '0', '0', 'common:file:download', '#', 'admin', sysdate(), '', null, ''),
(5179, '通用文件上传', 5016, 2, '#', null, null, '', 1, 0, 'F', '0', '0', 'common:file:upload', '#', 'admin', sysdate(), '', null, '')
on duplicate key update menu_name = values(menu_name), parent_id = values(parent_id), order_num = values(order_num), perms = values(perms), remark = values(remark);
